### ISSUE TITLE
Tap Error With Homebrew on macOS 

### ISSUE THREAD

**Issue by JosephLeedy** [roma-glushko/homebrew-tango#1]
# Expected Result

Tap is installed in Homebrew.

# Actual Result

The following error is thrown:
>==> Tapping roma-glushko/tango
Cloning into '/opt/homebrew/Library/Taps/roma-glushko/homebrew-tango'...
remote: Enumerating objects: 55, done.
remote: Total 55 (delta 0), reused 0 (delta 0), pack-reused 55
Receiving objects: 100% (55/55), 8.41 KiB | 4.21 MiB/s, done.
Resolving deltas: 100% (13/13), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/roma-glushko/homebrew-tango/Formula/tango.rb
tango: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the roma-glushko/tango tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/roma-glushko/homebrew-tango/Formula/tango.rb:6
>
>Error: Cannot tap roma-glushko/tango: invalid syntax in tap!

# Steps to Reproduce
1. Install Homebrew
2. Run `brew tap roma-glushko/tango`

# Environment
1. Mac Studio M1 Max
2. macOS Monterey 12.3.1
3. Homebrew 3.4.7

**Comment by roma-glushko** [comment]
Seems like a duplicate of https://github.com/roma-glushko/tango/issues/49. Will take a look at this one as well 🔍

**Comment by JosephLeedy** [comment]
Thank you. I didn't realize there was an existing issue on the main repo.

**Comment by roma-glushko** [comment]
Gonna fix this issue in scope of the following PR: https://github.com/roma-glushko/tango/pull/50

**Comment by roma-glushko** [comment]
@JosephLeedy Hey Joseph, have got some progress in fixing issues you have reported 🙌

I could install Tango on my macOS Monterey again:
<img width="1503" alt="Screenshot 2022-04-24 at 12 25 22" src="https://user-images.githubusercontent.com/9402690/164989369-e245fc20-69fa-4392-940d-ad0c6edb6f5d.png">

Can you please try it on your side? I have created a new version called 1.1.1-rc1 to try.

**Comment by JosephLeedy** [comment]
I've confirmed that I now able to tap and install Tango. I'll play with it and update #2.
