### ISSUE TITLE
Apple M1 Architecture Support

### ISSUE THREAD

**Issue by JosephLeedy** [roma-glushko/homebrew-tango#2]
Are there any plans to support the Apple M1 ARM architecture? I see that ARM is supported for Linux, so theoretically this should be possible.

**Comment by roma-glushko** [comment]
@JosephLeedy Hey Joseph, thank you for using Tango 💃 
Let me investigate this question. In any case, I would be happy to support as many platforms as possible and golang should be able to allow that.
Will let you know what I find.

**Comment by roma-glushko** [comment]
@JosephLeedy `darwin/arm64` seems to be supported by latest versions of golang. I'm going to make an upgrade in order to bring the support into Tango. Here is a WIP PR where I'm currently working on that: https://github.com/roma-glushko/tango/pull/50

**Comment by JosephLeedy** [comment]
That’s awesome, thank you.

**Comment by roma-glushko** [comment]
@JosephLeedy Hey Joseph, Tango 1.1.1-rc1 should now include darwin/arm64 build:

<img width="914" alt="Screenshot 2022-04-24 at 20 45 12" src="https://user-images.githubusercontent.com/9402690/164989434-7fbc25a2-20d4-453a-8a93-1da96589a716.png">

Can you please check if it works on your M1-compatible machine? Unfortunately, I'm still using the intel-based machine, so have no chance to double check.

**Comment by JosephLeedy** [comment]
Seems to work fine, thanks.
